# Generated by Django 5.0.1 on 2024-04-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='auctions.auction_lists'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to='auctions.auction_lists'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchedby', to='auctions.auction_lists'),
        ),
    ]
