# Generated by Django 5.0.1 on 2024-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_auction_alter_comments_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lists',
            name='category',
            field=models.ManyToManyField(related_name='auctions', to='auctions.category'),
        ),
    ]
